### ISSUE TITLE
Inconsistent variables for export function in io module

### ISSUE THREAD

**Issue by clemens-fricke** [tataratat/splinepy#359]
This regards the `mfem` export function. Here only a single spline (needs to be also a NURBS spline?) can be provided to the function in all other export functions a list of splines should be provided to the export function. 

Is `mfem` limited to only a single spline per file or could we adapt this function to also take a list of splines to make the interface more consistent?

**Comment by jzwar** [comment]
Uniform export is unfortunately not possible. The export formats like `mfem` and `gismo` export iga-meshes and thus need to provide interfaces and boundaries, so a Multipatch object is preferred. IRIT, json export splines, so a list can be provided, which allows for more flexibility, because you can export different `para-dims` and `dims`, `show_options` etc. 

As to MFEM: There are two different export functions for MFEM, one in cartesian format, that is more mesh-related, and one that only works for a single spline at the moment. We are still waiting for some changes in the MFEM file format, that makes some of the code deprecated. However, as this is still being worked on (supposedly) on the MFEM side, there is not much we can do about it.

I hope this answers you question, if so, I suggest moving this issue to discussion, as it is more of a development incentive rather than a bug/issue

**Comment by clemens-fricke** [comment]
Thank you for the in-depth explanation. This answers my question.
